### ISSUE TITLE
Unable to upload raw data due to dimension error

### ISSUE THREAD

**Issue by EntoSanchez** [aelefebv/nellie#14]
I am trying to select files with known dimensions. The pixel information is included in the files based on what FIJI is showing when I click properties; however, when I try to upload to nellie, it says "no X dimension found"

    188 if self.dim_sizes['X'] is None:
    189     logger.error('No X dimension found.')
--> 190     raise ValueError
    191 if self.dim_sizes['X'] != self.dim_sizes['Y']:
    192     logger.warning('X and Y dimensions do not match. Non-square pixels not supported, '
    193                    'so unexpected results and wrong measurements will occur.')

**Comment by aelefebv** [comment]
Hi Ento, any chance you can send me an example file that is creating this error to austin.e.lefebvre@gmail.com
This will help me debug it.

**Comment by EntoSanchez** [comment]
Sent it!

**Comment by aelefebv** [comment]
Just figured out the issue, it seems like for whatever reason the file has only some parts of the dimensions info in the imagej metadata, but we need to go to the tif tags to pull out the rest. In any case, I'll push an update soon, and it should work with no issue! (but let me know if you do run into issues)
