### ISSUE TITLE
type object 'XmlSerializer' has no attribute 'encode'

### ISSUE THREAD

**Issue by Amirhk-dev** [aelefebv/nellie#16]
Hi,
I have installed "Nellie" via the Napari plugin manager.
It is possible to select and visualize the file "yeast_3d_mitochondria.ome.tif" but
clicking "Run preprocessing" generates the "type object 'XmlSerializer' has no attribute 'encode'" error.

How is it possible to resolve this issue?

Below is part of the Traceback:

----------------------------------------------

AttributeError                            Traceback (most recent call last)
File /opt/anaconda3/envs/nellie_env/lib/python3.11/site-packages/nellie_napari/nellie_processor.py:186, in NellieProcessor.run_preprocessing(self=<nellie_napari.nellie_processor.NellieProcessor object>)
    183 def run_preprocessing(self):
    184     preprocessing = Filter(im_info=self.nellie.im_info, num_t=self.num_t,
    185                            remove_edges=self.remove_edges_checkbox.isChecked())
--> 186     preprocessing.run()
        preprocessing = <nellie.segmentation.filtering.Filter object at 0x2d8ae6150>
    188     self.check_file_existence()

----------------------------------------------

Thanks.

**Comment by aelefebv** [comment]
Hi Amir, weird I haven't seen this error before. Can you send the file to austin.e.lefebvre@gmail.com if possible?
I'll take a look.

**Comment by Amirhk-dev** [comment]
Hi Austin,
I just sent the email.
Thank you.
