### ISSUE TITLE
CUDA Runtime Error

### ISSUE THREAD

**Issue by nogapreminger** [aelefebv/nellie#18]
Hey,

I tried running Nellie and got the following error:
```
CUDARuntimeError: cudaErrorInsufficientDriver: CUDA driver version is insufficient for CUDA runtime version
```

Even before running Nellie, when I activate Napari I get the following:
``` 
>napari
C:\Users\AppData\Local\miniconda3\envs\napari-env\lib\site-packages\cupy\_environment.py:216: UserWarning: CUDA path could 
not be detected. Set CUDA_PATH environment variable if CuPy fails to load.
  warnings.warn(...
```

I have these installed in my environment:
```
cuda-python               12.4.0                   pypi_0    pypi
cupy-cuda12x              13.0.0                   pypi_0    pypi
```

I would love to get some help with this. Let me know if you need any other details to understand the issue.
Thanks!

**Comment by aelefebv** [comment]
Hello!
It looks like maybe you need to install a compatible version of some CUDA drivers.

try to install it from here, based on your operating system. It looks like you pip installed the 12x version. I believe it needs to be 12.2 or lower to be compatible, so I’d recommend downloading the 12.2 version.
https://developer.nvidia.com/cuda-toolkit

Let me know if that fixes it!

**Comment by aelefebv** [comment]
Closing for now. Feel free to reopen if unresolved.
