### ISSUE TITLE
Analysis tab data on images?

### ISSUE THREAD

**Issue by ChengzheDuan** [aelefebv/nellie#24]
Hello, I was wondering if it's possible to get all the analysis tab data for images (without T resolution).

**Comment by aelefebv** [comment]
Hi Chengzhe, can you give a little more info on what you are trying to do?
It sounds like maybe you are not able to export your data without a time series dataset?
Does this mean you are not able to open the analysis tab when running a dataset without T?

**Comment by ChengzheDuan** [comment]
Yes.

When I uploaded an image and clicked "Run Nellie", I got this error:
![Screenshot 2024-06-12 at 9 05 26 PM](https://github.com/aelefebv/nellie/assets/130731114/0ac7d2f6-3f92-4ddb-a052-6634b0d862cf)
Complete error message:
![image](https://github.com/aelefebv/nellie/assets/130731114/92fd2334-8a01-4f6d-8547-ec6022f1a407)

It makes sense because there is no T in my image. I was able to run the first three individual steps successfully (run processing, run segmentation, and run mocap marking). At this point, the Analyze tab is "unclickable":
![image](https://github.com/aelefebv/nellie/assets/130731114/36f17e70-fb67-4780-b906-726874a8accb)

**Comment by aelefebv** [comment]
I think I know the problem. It looks like it is indeed trying to run tracking even without only 1 temporal frame.
Can you send me the file that causes this error? austin.e.lefebvre+nellie@gmail.com
I'll fix it up asap.
